create TABLE IF NOT EXISTS mainmenu(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
url TEXT NOT NULL
);


create TABLE IF NOT EXISTS products(
id INTEGER PRIMARY KEY AUTOINCREMENT,
product TEXT NOT NULL,
price INTEGER NOT NULL,
image BLOB DEFAULT NULL,
time INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
nickname TEXT NOT NULL,
email TEXT NOT NULL,
psw INTEGER NOT NULL,
avatar BLOB DEFAULT NULL,
time INTEGER NOT NULL
)
